stages:
- name: build
  steps:
  - runScriptConfig:
      image: golang:latest
      shellScript: go build -o demo
- name: push
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: rio-demo
timeout: 60
notification: {}
